package CLient;


//import static CLient.CLient.br;
//import static CLient.CLient.din;
//import static CLient.CLient.dout;
//import static CLient.CLient.s;
//import static CLient.CLient.str;
import static CLient.CLient.textArea;
import CLient.friends;
import static CLient.friends.chat;
import static CLient.friends.friendChat;
import static CLient.friends.friendsList;
import static CLient.friends.friendsNum;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.StringTokenizer;


public class name extends javax.swing.JFrame {
public  static Socket s;
   public  static DataInputStream din;
   public   static DataOutputStream dout;
   public static BufferedReader br;
   public  static String str="",str2="", screen="";
   
   
    public static String Name;
    public name() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 450));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        textName.setBackground(new java.awt.Color(204, 204, 255));
        textName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textName.setForeground(new java.awt.Color(102, 102, 102));
        textName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textName.setText("enter your name");
        textName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNameMouseClicked(evt);
            }
        });
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        jPanel1.add(textName);
        textName.setBounds(96, 149, 376, 62);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("join");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(175, 262, 214, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Client\\img\\Picture1.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 30, 116, 95);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        textName.setText("");
    }//GEN-LAST:event_textNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Name = textName.getText();
        try {
        dout.writeUTF("@" + Name); // ## <- hash to name
            dout.flush();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        this.setVisible(false);
        new friends().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNameMouseClicked
      textName.setText("");
    }//GEN-LAST:event_textNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new name().setVisible(true);
            }
        });
          s=new Socket("localhost",2020);
        din=new DataInputStream(s.getInputStream());
        dout=new DataOutputStream(s.getOutputStream());
         br=new BufferedReader(new InputStreamReader(System.in));
        
         
         
  while(true)
{

str2=din.readUTF();

  String sendName="";
  String msg="";
    System.out.println("msg come");
   StringTokenizer st =new StringTokenizer(str2,"#");
   
   sendName = st.nextToken();
   msg = st.nextToken();

   int IDfriend = 1;
   
   for (int i=0; i<=friendsNum+5 ; ++i)
   {
       if (friendsList[i].equals(sendName)) {
           System.out.println("found");
           IDfriend = i;
       }
       
   }

chat[IDfriend] += "\n"+ sendName +" : "+msg;

if (IDfriend == friendChat)
textArea.setText(chat[friendChat]);

}

//dout.close();
//s.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
